### ISSUE TITLE
[Issue]: Font Always reset to size 12

### ISSUE THREAD

**Issue by FartyPants** [Nevysha/Cozy-Nest#136]
### What happened?

It could be just me
I go to settings, set font to 14, hit save.
Next time (or on UI reload, the font is 12 again)

the font is written correctly in settings nevyui_settings.json
"font_size": 14,
But again, next time I run it - font is 12
Nice theme, but on my monitor, I can't see font 12 very well

### Webui

Automatic1111's webui

### What browsers are you seeing the problem on?

Firefox

### Additional info

A bug happened!

### Checklist

- [X] I have searched the issues to make sure this is not a duplicate
- [X] Webui is up to date
- [X] Cozy-Nest is up to date
- [X] All my extensions are up to date

**Comment by Nevysha** [comment]
It happen when you use "Reload UI" or even on restart ?

**Comment by jeditobe1** [comment]
I am having this with all settings - it is writing to the config file, but not using the settings it writes.

Refresh Page, Reload UI, and restarting A1111 all reset back to default settings (but don't write the file unless those settings are saved).

I had added some minor debugging via prints to the setting load scripts, and from what I can tell they are being loaded.  Using the "accent generate button" as a test case - it had the right setting when setting up the checkbox in the gradio_main_tab() method in nevysha_cozy_nest.py, but still did not show on the UI.  Even hardcoding it to use a "true" value there rather than reading from config did not cause the checkbox to be checked.

I have a different A1111 setup on a different machine, also on 2.1.6, and it loads/saves settings just fine (one is a windows install, the other is a linux install).  At a guess it is a race condition (UI finishes spinning up before settings are loaded), but I am not familiar enough with the code to debug further.

**Comment by FartyPants** [comment]
> It happen when you use "Reload UI" or even on restart ?
Exactly just like [jeditobe1](https://github.com/jeditobe1)
all prams save fine, but then never load and everything is reset to default.
Tried firefox and chrome

**Comment by Nevysha** [comment]
Can you try the new update I just pushed and tell me if it works ? (v2.1.7)

**Comment by jeditobe1** [comment]
Looks much happier - booted with the settings previously saved, and editing the settings and saving then reloading UI also worked.
