### ISSUE TITLE
Drop-down menus are now too tiny

### ISSUE THREAD

**Issue by ostap667inbox** [Nevysha/Cozy-Nest#85]
[569ee22](https://github.com/Nevysha/Cozy-Nest/commit/569ee22eb8a30e09d7294c8f0a1e1ba11aa2013c)
The height of the drop-down menus has decreased several times. Now it is very inconvenient to use long lists of models or preprocessors in ControlNet.
There is no such problem with Cozy Nest disabled.
A little more room for the lists, huh? :)

![cn-on](https://github.com/Nevysha/Cozy-Nest/assets/123593542/365f311a-b1c1-413b-acf1-432ba2d17297)
![cn-off](https://github.com/Nevysha/Cozy-Nest/assets/123593542/a9cb47f9-7e91-4023-a036-d91243f3dd91)

**Comment by mukolah** [comment]
As a temporary solution you can also click "Extra networks" on the right side and view "Checkpoints" tab I believe it would be much more easier to scroll, at least for now until bug is fixed

**Comment by ostap667inbox** [comment]
> As a temporary solution you can also click "Extra networks" on the right side and view "Checkpoints" tab. I believe it would be much more easier to scroll, at least for now until bug is fixed

The same change has affected other drop-down menus as well. For example, in ControlNet the lists of preprocessors and models. There are no alternative ways to display the list there.

**The fact that it takes longer to scroll through a small drop-down list isn't really the main problem at all.**

**Why is it good to have a lot of entries in the drop-down list?** Sometimes users have hundreds of checkpoints. It's absolutely impossible to keep all the names in your head, but when we come across an entry in the drop-down list, we recognize it. If the drop-down list shows, for example, only 5% of the total number of records at a time, the user will have to remember the exact names to scroll down the list to the right one, or if he can't remember the exact name, he may have to scroll down the entire list several times until he comes across the right record, this is very stressful. Again, this is relevant when you have hundreds of items in the list.

And in other builds, such as Vlad, this is further exacerbated by bugs in the build itself. His checkpoints list are displayed with the name of the subdirectory - it's a hell.

**Comment by mukolah** [comment]
I understand your concern and I'm not saying it should not be fixed, obviously it is best when more elements visible on screen. The reason why it is like this right now is because of the bug due to which styles and scripts menu when they are too long they clip through background... Hard to explain, but it will be fixed, I'm sure of that!

**Comment by Nevysha** [comment]
Hey !
Can you update through extension tab and see if this problem is fixed for you ? I made a workaround that fix the dropdown list above everything. It's totally hacky and dirty and won't resist page scroll tho (options will stay fixed when openned). But the dropdown should now be bigger. @ostap667inbox @mukolah 

I did not update the version number. I'm waiting for your confirm on that.

**Comment by mukolah** [comment]
Works like a charm, thank you!
