### ISSUE TITLE
lora_subdirs is hidden

### ISSUE THREAD

**Issue by bluelovers** [Nevysha/Cozy-Nest#88]
![image](https://github.com/Nevysha/Cozy-Nest/assets/167966/487327dd-af10-47d4-bfeb-12aef510b60c)

**Comment by tsound97** [comment]
Same here. This problem occurs when the name of the subdirs is long. Maybe you can add an option to let users choose whether to display the subdirs horizontally or vertically.

**Comment by mukolah** [comment]
Tried all browsers but was never able to achieve result that is on screenshot, literally hit maximum name path for folder. Still the design didn't made much sense to be vertical like that especially considering variable size of Extra Networks window.
Fixed in dev, changed it to horizontal, still looks Cozy
More details: https://github.com/Nevysha/Cozy-Nest/pull/89#issuecomment-1549090231
