### ISSUE TITLE
Settings window opens and closes quickly

### ISSUE THREAD

**Issue by rethink-studios** [Nevysha/Cozy-Nest#91]
Hi,
On Chrome, the settings menu opens on click, but immediately closes.

Video below:
https://www.dropbox.com/s/63a11tuou89valm/COZY_SETTINGS_ERROR.mov?dl=0

**Comment by VelvetAcidChrist** [comment]
Me too

**Comment by mukolah** [comment]
Already mentioned in: https://github.com/Nevysha/Cozy-Nest/issues/66
@Nevysha I think there could be 2 problems, one may be that it registering for some reason settings button as double click or maybe some browser/OS combo are bugging due to "click outside of the window to close". Probably easiest solution to ensure compatibility would be to ditch closing outside of the window as well by pushing settings second time and only make it close by onclick event at "Close" button, what do you think?

**Comment by Ataraksia** [comment]
It's not a browser or OS combo as far as I can tell.  Tested Chromium and Firefox on both Windows and Linux to same effect.

Tested your solution and removing the "hide it on click outside" code did indeed solve the problem. 

Alright, so after a frustrating amount of time spent on this, I've determined that it's actually an interaction between this and @vladmandic [system info](https://github.com/vladmandic/sd-extension-system-info) extension that's causing the behavior, at least on my particular setup.  Hopefully this will be of benefit, too sleepy for any additional testing.

**Comment by vladmandic** [comment]
system info extension uses javascript `IntersectionObserver` to detect if its visible or not so it refresh settings like memory usage in a frequent polling call only when needed. i'm guessing that javascript code is interfering with this solution?

**Comment by halfblack** [comment]
> 

Disabled System Info, issue is gone. Thanks!

**Comment by Nevysha** [comment]
Should be good now if you update. Thanks for the help !
